In [98]:
# Import python libraries 
import pandas as pd
import csv
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
import nltk
import time
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from nltk.stem.snowball import SnowballStemmer

In [99]:
# Import test and train data
path = '/Users/zgalvin/Desktop/Kaggle Problem/train.csv'
pathTrain = '/Users/zgalvin/Desktop/Kaggle Problem/test.csv'

trainData = pd.read_csv(path, names=['ID', 'Text', 'Toxic','Severe_Toxic','Obscene', 'Threat', 'Insult', 'Identity_Hate'], low_memory = False, header=0)
testData = pd.read_csv(pathTrain, names=['ID','Text'],header=0,dtype={'ID': str})

trainData.head()

ID                                               Text  Toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   Severe_Toxic  Obscene  Threat  Insult  Identity_Hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [100]:
# Split the data up into X and y

# Start timer
start_time = time.time()

# Assign text to X and categories to y
X_train = trainData.Text
y_train = [trainData.Toxic, trainData.Severe_Toxic, trainData.Obscene, trainData.Threat, trainData.Insult, trainData.Identity_Hate]

# Assign text to X in the test set
X_test = testData.Text

elapsed_time = time.time() - start_time
print(elapsed_time)

0.008777856826782227


In [101]:
# Turn text to numbers

# Start timer
start_time = time.time()
'''
# Create Lemmatizer
class LemmaTokenizer(object):
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, doc):
        return [self.wnl.lemmatize(t) for t in word_tokenize(doc)]
'''        

# Fit and transform X into tokenized word counts
count_vect = CountVectorizer(stop_words='english', min_df=.0002, max_df=.9)
X_train = count_vect.fit_transform(X_train)
# print(count_vect.get_feature_names())
print(X_train.shape)
print(type(X_train))

# Create sparse matrix of character counts for each comment
count_vect_char = CountVectorizer(stop_words='english', analyzer='char')
X_train_char = count_vect_char.fit_transform(trainData.Text)
# print(count_vect_char.get_feature_names())
print(X_train_char.toarray())
print(type(X_train_char))

# Implement term frequency–inverse document frequency on the word counts (this did not help accuracy)
# tf_transformer = TfidfTransformer()
# X_train = tf_transformer.fit_transform(X_train_counts)

elapsed_time = time.time() - start_time
print(elapsed_time)

(159571, 10712)
<class 'scipy.sparse.csr.csr_matrix'>
[[ 1 41  0 ...  0  0  0]
 [ 0 16  1 ...  0  0  0]
 [ 0 41  0 ...  0  0  0]
 ...
 [ 0 11  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 1 34  0 ...  0  0  0]]
<class 'scipy.sparse.csr.csr_matrix'>
22.95152497291565


In [102]:
# Stack the word and character sparse matrices
'''from scipy.sparse import vstack
stackedX = vstack([X_train,X_train_char])
print(stackedX)
print(type(stackedX))
'''

'from scipy.sparse import vstack\nstackedX = vstack([X_train,X_train_char])\nprint(stackedX)\nprint(type(stackedX))\n'

In [103]:
# Transform X_test

# Start timer
start_time = time.time()

# Transform X for the training data into tokenized word counts
X_test = count_vect.transform(X_test)
print(X_test.shape)
print(type(X_test))

# Transform X in testing data througb frequency–inverse document frequency on the word counts (this did not help accuracy)
# X_test = tf_transformer.transform(X_test)

elapsed_time = time.time() - start_time
print(elapsed_time)

(153164, 10712)
<class 'scipy.sparse.csr.csr_matrix'>
7.421841859817505


In [104]:
# Function to choose model so that editing models is easier (less copy and pasting)

# Start timer
start_time = time.time()

def chooseModel(model,y):
    if model == "nb":
        # use MultinomialNB
        mlb = MultinomialNB()
        print(elapsed_time)
        return mlb
    elif model == "sgd":
        # use SGDClassifier 
        sgd = SGDClassifier()
        print(elapsed_time)
        
        '''# Define parameters to optimize
        params = dict(loss=['log','modified_huber', 'squared_hinge', \
                            'perceptron', 'squared_loss', 'huber', \
                            'epsilon_insensitive', 'squared_epsilon_insensitive'],\
                            penalty=['none','l2','l1','elasticnet'], \
                            alpha=(1e-2, 1e-3), fit_intercept=[True,False]  
                     )
        
        rand = RandomizedSearchCV(sgd, params, n_iter=5, random_state=5)
        rand.fit(X_train, y_train[y])
        
        # Print out the optimal parameters 
        print(rand.best_params_)
        
        # Instatiate new model with optimized parameters
        sgd = SGDClassifier(loss=rand.best_params_['loss'], penalty=rand.best_params_['penalty'])
        '''
        return sgd
    elif model == "randTree":
        # Use RandomForestClassifier
        rfc = RandomForestClassifier(n_estimators=10)
        print(elapsed_time)
        return rfc
    elif model == "decTree":
        # Use DecisionTreeClassifier
        dtc = DecisionTreeClassifier()
        print(elapsed_time)
        return dtc
    else:
        print("Sorry! We have not implemented that model yet.")


In [105]:
# Test model on each category

# Start timer
start_time = time.time()

# Identity_Hate
mlb = chooseModel(model="nb",y=5).fit(X_train, y_train[5])
predicted_Identity_Hate = mlb.predict_proba(X_test)
predicted_Identity_Hate = pd.Series(predicted_Identity_Hate[:,1])

# Insult
mlb = chooseModel(model="nb",y=4).fit(X_train, y_train[4])
predicted_Insult = mlb.predict_proba(X_test)
predicted_Insult = pd.Series(predicted_Insult[:,1])

# Threat
mlb = chooseModel(model="nb",y=3).fit(X_train, y_train[3])
predicted_Threat = mlb.predict_proba(X_test)
predicted_Threat = pd.Series(predicted_Threat[:,1])

# Obscene
mlb = chooseModel(model="nb",y=2).fit(X_train, y_train[2])
predicted_Obscene = mlb.predict_proba(X_test)
predicted_Obscene = pd.Series(predicted_Obscene[:,1])

# Severly Toxic
mlb = chooseModel(model="nb",y=1).fit(X_train, y_train[1])
predicted_Severly_Toxic = mlb.predict_proba(X_test)
predicted_Severly_Toxic = pd.Series(predicted_Severly_Toxic[:,1])

# Toxic
mlb = chooseModel(model="nb",y=0).fit(X_train, y_train[0])
predicted_Toxic = mlb.predict_proba(X_test)
predicted_Toxic = pd.Series(predicted_Toxic[:,1])
'''
cols = ['predicted_Toxic','predicted_Severely_Toxic','predicted_Obscene','predicted_Threat','predicted_insult','predicted_Identity_Hate']
for i in range(len(y_train)):
    mlb = MultinomialNB().fit(X_train, y_train[i])
    # Transform X and then predict
    if i == 0:
        X_test = count_vect.transform(X_test)
        X_test = tf_transformer.transform(X_test)
    cols[i] = pd.Series(mlb.predict(X_test))
'''
elapsed_time = time.time() - start_time
print(elapsed_time)

7.421841859817505
7.421841859817505
7.421841859817505
7.421841859817505
7.421841859817505
7.421841859817505
0.7206511497497559


In [106]:
# Write data to csv file in Kaggle format

# Start timer
start_time = time.time()

# Create list of column names (How Kaggle wants it)
columnNames = 'id','toxic','severe_toxic','obscene', 'threat', 'insult', 'identity_hate'

# Concat the pandas series together to create a data frame
data = pd.concat([testData.ID,predicted_Toxic,predicted_Severly_Toxic,predicted_Obscene,predicted_Threat,predicted_Insult,predicted_Identity_Hate], axis=1)
data.head()

# Write data frame to the result.csv on desktop
data.to_csv(path_or_buf='/Users/zgalvin/Desktop/results.csv', index=False, header=columnNames)

elapsed_time = time.time() - start_time
print(elapsed_time)


2.5390448570251465
